swapped output variables in main to directly access array, cleaned up comments

diff --git a/gasmask b/gasmask
--- a/gasmask
+++ b/gasmask
@@ -125,9 +125,9 @@ validate_cidr() {
   # ARG $1: cidr
   # RET: 0=valid, 1=fail
 
-  [[ "$1" == "0" ]] && return 0
-  [[ "$1" =~ ^[0-9]+$ && "$1" -ge 0 && "$1" -le 32 ]] && \
-    ! [[ "$1" =~ ^0[0-9] ]] && return 0
+  if [[ "$1" =~ ^([1-9]|[1-2][0-9]|3[0-2])$|^0$ ]]; then
+    return 0
+  fi
 
   err "CIDR notations must be a number between 0 and 32 inclusive!"
   return 1
@@ -207,39 +207,36 @@ validate_wildcard() {
   return 1
 }
 
-validate_ip_address_extra_error() {
-  # extra error message for validate_ip_address function
-  echo "IP addresses take the form \"xxx.xxx.xxx.xxx\" where each octet"
-  echo "must be between 0 and 255 inclusive!"
-}
-
 validate_ip_address() {
   # assess if a given ip address is a valid ipv4 address
   #
   # ARG $1: ip address
   # RET: 0 = valid ip address, 1 = invalid ip address
 
+  local -r extra_error_msg="IP addresses take the form \"xxx.xxx.xxx.xxx\"
+where each octet must be between 0 and 255 inclusive!"
+
   if ! [[ "$1" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]; then
     err "\"${1}\" is not a valid IP address!"
-    validate_ip_address_extra_error >&2
+    echo -e "$extra_error_msg" >&2
     return 1
   fi
 
   local -a ip_array=()
-  # convert ip address to array
+
   IFS='.' read -r -a ip_array <<< "$1"
 
   local octet_value=""
   for octet_value in "${ip_array[@]}"; do
     if [[ "$octet_value" != "0" && "$octet_value" =~ ^0 ]]; then
       err "\"${1}\" is not a valid IP address!"
-      validate_ip_address_extra_error >&2
+      echo -e "$extra_error_msg" >&2
       return 1
     fi
 
     if (( octet_value < 0 || octet_value > 255 )); then
       err "\"${1}\" is not a valid IP address!"
-      validate_ip_address_extra_error >&2
+      echo -e "$extra_error_msg" >&2
       return 1
     fi
   done
@@ -253,7 +250,7 @@ cidr_to_subnetmask() {
   # ARG $1: a cidr value
   # RET: subnet mask
 
-  # since we will operate on $1, reassign it now
+  # reassign $1 since we operate on it
   local cidr="$1" subnet_mask=""
 
   for (( i=0; i<4; i++ )); do
@@ -301,7 +298,7 @@ wildcard_to_subnetmask() {
 
   local -a wildcard_array=()
   local subnet_mask=""
-  # convert wildcard bit to array of octets
+
   IFS='.' read -r -a wildcard_array <<< "$1"
 
   for (( i=0; i<4; i++ )); do
@@ -327,8 +324,11 @@ subnetmask_to_cidr() {
       "0^^^128^192^224^240^248^252^254^" \
       "$(( (${#1} - ${#trailing_octets})*2 ))" \
       "${trailing_octets%%.*}"
+  # remove the leading part of the CIDR array up to the first non-255 octet
   trailing_octets="${1%%"${3}"*}"
 
+  # add number of leading 255 octets * 2 to
+  # the number of bits set in the first non-255 octet
   echo -n "$(( ${2} + (${#trailing_octets}/4) ))"
 }
 
@@ -340,7 +340,6 @@ subnetmask_to_hex() {
 
   local -a subnet_array=()
   local hex="" hex_pair=""
-  # convert subnet mask to array of octets
   IFS='.' read -r -a subnet_array <<< "$1"
 
   local octet_value=""
@@ -362,7 +361,7 @@ subnetmask_to_wildcard() {
 
   local -a subnet_array=()
   local wildcard=""
-  # convert subnet mask to array of octets
+
   IFS='.' read -r -a subnet_array <<< "$1"
 
   for (( i=0; i<4; i++ )); do
@@ -394,11 +393,10 @@ get_ip_network_address() {
   local -a ip_array=()
   local -a subnet_array=()
   local network_address=""
-  # convert IP and mask to arrays
+
   IFS='.' read -r -a ip_array <<< "$1"
   IFS='.' read -r -a subnet_array <<< "$2"
 
-  # calculate network address
   for (( i=0; i<4; i++ )); do
     local octet_value=""
     octet_value=$(( ip_array[i] & subnet_array[i] ))
@@ -420,7 +418,6 @@ get_ip_broadcast_address() {
   local -a subnet_array=()
   local broadcast_address=""
 
-  # convert IP and mask to arrays
   IFS='.' read -r -a ip_array <<< "$1"
   IFS='.' read -r -a subnet_array <<< "$2"
 
@@ -474,20 +471,15 @@ gather_gasmask_cidr() {
   # ARG $1: cidr
   # RET: cidr, subnet mask, subnet mask hexadecimal, wildcard bit, usable ips
 
-  local cidr="$1"
-  # removing leading zeros unless input is exactly '0'
-  [[ "$cidr" != "0" && "$cidr" =~ ^0 ]] && cidr="${cidr##0}"
-
-  # validate entered cidr
-  validate_cidr "$cidr" || return 1
+  validate_cidr "$1" || return 1
 
   local subnet_mask="" hex="" wildcard="" usable_ips=""
-  subnet_mask="$(cidr_to_subnetmask "$cidr")"
+  subnet_mask="$(cidr_to_subnetmask "$1")"
   hex="$(subnetmask_to_hex "$subnet_mask")"
   wildcard="$(subnetmask_to_wildcard "$subnet_mask")"
-  usable_ips="$(cidr_to_no_ips "$cidr")"
+  usable_ips="$(cidr_to_no_ips "$1")"
 
-  echo -n "$cidr $subnet_mask $hex $wildcard $usable_ips"
+  echo -n "$1 $subnet_mask $hex $wildcard $usable_ips"
 }
 
 gather_gasmask_subnet() {
@@ -496,7 +488,6 @@ gather_gasmask_subnet() {
   # ARG $1: subnet mask
   # RET: cidr, subnet mask, subnet mask hexadecimal, wildcard bit, usable ips
 
-  # validate entered subnet mask
   validate_subnet "$1" || return 1
 
   local cidr="" hex="" wildcard="" usable_ips=""
@@ -514,7 +505,6 @@ gather_gasmask_hex() {
   # ARG $1: subnet mask
   # RET: cidr, subnet mask, subnet mask hexadecimal, wildcard bit, usable ips
 
-  # validate entered hex
   validate_hex "$1" || return 1
 
   local cidr="" subnet_mask="" wildcard="" usable_ips=""
@@ -532,7 +522,6 @@ gather_gasmask_wildcard() {
   # ARG $1: wildcard bit
   # RET: cidr, subnet mask, subnet mask hexadecimal, wildcard bit, usable ips
 
-  # validate entered wildcard
   validate_wildcard "$1" || return 1
 
   local cidr="" subnet_mask="" hex="" usable_ips=""
@@ -551,7 +540,6 @@ gather_gasmask_ip() {
   # ARG $2: subnet mask
   # RET: ip addr, network addr, broadcast addr, first usable ip, last usable ip
 
-  # validate entered ip address
   validate_ip_address "$1" || return 1
 
   local network_address="" broadcast_address="" first_usable="" last_usable=""
@@ -560,11 +548,12 @@ gather_gasmask_ip() {
   first_usable="$(get_ip_first_address "$network_address" "$2")"
   last_usable="$(get_ip_last_address "$broadcast_address" "$2")"
 
-  echo -n "$1 $network_address $broadcast_address $first_usable $last_usable"
+  echo -n "$network_address $broadcast_address $first_usable $last_usable"
 }
 
 main() {
   set -eu
+
   # check for no argument
   if [[ $# -eq 0 ]]; then
     show_noarg
@@ -585,12 +574,10 @@ main() {
     input_subnet_value="$1"
     ip_address=""
     whatmask_mode="1"
-  fi
-
-  # check if a "/" is present in $1. If so, split $1 into
-  # $ip_address and $input_subnet_value
-  # mode 2 means that we did get an ip address in $1
-  if [[ "$1" =~ "/" ]]; then
+  else
+    # check if a "/" is present in $1. If so, split $1 into
+    # $ip_address and $input_subnet_value
+    # mode 2 means that we did get an ip address in $1
     input_subnet_value="${1#*/}"
     ip_address="${1%/*}"
     # if a slash was used without an ip address, then it's still assigned mode 1
@@ -601,33 +588,29 @@ main() {
 
   local input_subnet_type=""
   # determie what initial subnet value given
-  input_subnet_type=$(subnet_which_initial "$input_subnet_value")
+  input_subnet_type="$(subnet_which_initial "$input_subnet_value")"
 
-  local subnet_all=""
+  # this case gathers subnet information
+  local -a gasmask_subnet_array=()
+  local subnet_info=""
   case "$input_subnet_type" in
-    cidr) subnet_all="$(gather_gasmask_cidr "$input_subnet_value")" ;;
-    subnetmask) subnet_all="$(gather_gasmask_subnet "$input_subnet_value")" ;;
-    hex) subnet_all="$(gather_gasmask_hex "$input_subnet_value")" ;;
-    wildcard) subnet_all=$(gather_gasmask_wildcard "$input_subnet_value") ;;
+    cidr) subnet_info="$(gather_gasmask_cidr "$input_subnet_value")" ;;
+    subnetmask) subnet_info="$(gather_gasmask_subnet "$input_subnet_value")" ;;
+    hex) subnet_info="$(gather_gasmask_hex "$input_subnet_value")" ;;
+    wildcard) subnet_info="$(gather_gasmask_wildcard "$input_subnet_value")" ;;
   esac
-
-  # this block gathers subnet information
-  local subnet_cidr="" subnet_mask="" subnet_hex="" subnet_wildcard=""
-  local subnet_usable=""
-  IFS=' ' read -r \
-     subnet_cidr subnet_mask subnet_hex subnet_wildcard subnet_usable \
-     <<< "$subnet_all"
+  # read output from above into an array
+  # we separated the output into a variable first instead of directly into array
+  # to gracefully handle errors
+  IFS=' ' read -r -a gasmask_subnet_array <<< "$subnet_info"
 
   if [[ "$whatmask_mode" -eq 2 ]]; then
-    local ip_all_output=""
-    ip_all_output=$(gather_gasmask_ip "$ip_address" "$subnet_mask")
-
-    # this block gathers ip information when ip address is used with gasmask
-    local network_address="" broadcast_address=""
-    local first_address="" last_address=""
-    IFS=' ' read -r \
-       ip_address network_address broadcast_address first_address last_address \
-       <<< "$ip_all_output"
+    # below gathers ip information into an array
+    local -a gasmask_ip_array=()
+    local ip_info=""
+    ip_info="$(gather_gasmask_ip "$ip_address" "${gasmask_subnet_array[1]}")"
+    # gasmask_subnet_array[1] is the subnet mask value
+    IFS=' ' read -r -a gasmask_ip_array <<< "$ip_info"
   fi
 
   if [[ "$whatmask_mode" -eq 1 ]]; then
@@ -635,11 +618,11 @@ main() {
     echo "---------------------------------------------"
     echo "       TCP/IP SUBNET MASK EQUIVALENTS"
     echo "---------------------------------------------"
-    echo "CIDR = .....................: /$subnet_cidr"
-    echo "Netmask = ..................: $subnet_mask"
-    echo "Netmask (hex) = ............: $subnet_hex"
-    echo "Wildcard Bits = ............: $subnet_wildcard"
-    printf "Usable IP Addresses = ......: %'d\n" "$subnet_usable"
+    echo "CIDR = .....................: /${gasmask_subnet_array[0]}"
+    echo "Netmask = ..................: ${gasmask_subnet_array[1]}"
+    echo "Netmask (hex) = ............: ${gasmask_subnet_array[2]}"
+    echo "Wildcard Bits = ............: ${gasmask_subnet_array[3]}"
+    printf "Usable IP Addresses = ......: %'d\n" "${gasmask_subnet_array[4]}"
     echo ""
   fi
 
@@ -649,16 +632,16 @@ main() {
     echo "           TCP/IP NETWORK INFORMATION"
     echo "------------------------------------------------"
     echo "IP Entered = ..................: $ip_address"
-    echo "CIDR = ........................: /$subnet_cidr"
-    echo "Netmask = .....................: $subnet_mask"
-    echo "Netmask (hex) = ...............: $subnet_hex"
-    echo "Wildcard Bits = ...............: $subnet_wildcard"
+    echo "CIDR = ........................: /${gasmask_subnet_array[0]}"
+    echo "Netmask = .....................: ${gasmask_subnet_array[1]}"
+    echo "Netmask (hex) = ...............: ${gasmask_subnet_array[2]}"
+    echo "Wildcard Bits = ...............: ${gasmask_subnet_array[3]}"
     echo "------------------------------------------------"
-    echo "Network Address = .............: $network_address"
-    echo "Broadcast Address = ...........: $broadcast_address"
-    printf "Usable IP Addresses = .........: %'d\n" "$subnet_usable"
-    echo "First Usable IP Address = .....: $first_address"
-    echo "Last Usable IP Address = ......: $last_address"
+    echo "Network Address = .............: ${gasmask_ip_array[0]}"
+    echo "Broadcast Address = ...........: ${gasmask_ip_array[1]}"
+    printf "Usable IP Addresses = .........: %'d\n" "${gasmask_subnet_array[4]}"
+    echo "First Usable IP Address = .....: ${gasmask_ip_array[2]}"
+    echo "Last Usable IP Address = ......: ${gasmask_ip_array[3]}"
     echo ""
   fi
 }
